config/routes.rb
Rails.application.routes.draw do
  #get 'track/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'tracks#index'

  #get 'track#new'

  resources :tracks

  resources :drivers

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/driver.rb
class Driver < ApplicationRecord
  has_many :tracks

  validates_each :name, :surname do |record, attr, value|
    record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
  end
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :driver

  validates :driver, presence:true
  validates :start, :destination, presence: { message: "Objekt jest pusty" }, length: { minimum: 2 } # :column_name, method: argument
  validates :distance, numericality: { greater_than: 0, message: "Dystans musi być większy od ZERA" }
  validates :date, presence: { message: "Objekt jest pusty" }

  validate :date_cannot_be_in_the_future

  def date_cannot_be_in_the_future
    if date.present? && date > Date.today
      errors.add(:date, "Nie można wpisać podróży z przyszłości")
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController

  def new
    @driver = Driver.new
  end

  def create
    @driver = Driver.new(driver_params)
    @driver.save
    redirect_to drivers_path
  end

  def edit
    @driver = Driver.find(params[:id])
  end

  def update
    @driver = Driver.find(params[:id])
    if @driver.update(driver_params)
      redirect_to(@driver)
    else
      render :edit
    end
  end

  def show
    @driver = Driver.find(params[:id])
  end

  def index
    @drivers = Driver.all
  end

  private
  def driver_params
   params.require(:driver).permit(:name, :surname, :address)
  end

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  def new
    @track = Track.new
  end

  def create
    @track = Track.new(track_params)

    @track.save
    redirect_to tracks_path
  end

  def edit
    @track = Track.find(params[:id])
  end

  def update
    @track = Track.find(params[:id])
    if @track.update(track_params)
      redirect_to(@track)
    else
      render :edit
    end
  end

  def show
    @track = Track.find(params[:id])
  end

  def index
    @tracks = Track.all
  end

  private

  def track_params
    params.require(:track).permit(:start, :destination, :car, :distance, :description, :driver_id, :date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/track_helper.rb
module TrackHelper
end

app/views/drivers/edit.html.erb
<h1 class="my-4"> Edytuj kierwce </h1>

<%= form_for @driver do |form| %>
  <p>
    <%= form.label :name, "Imie" %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :surname, "Nazwisko" %><br>
    <%= form.text_field :surname %>
  </p>

  <p>
    <%= form.label :address, "Adres" %><br>
    <%= form.text_field :address %>
  </p>

  <p>
    <%= form.submit "Zapisz", class: "btn btn-success" %>
  </p>
<% end %>

app/views/drivers/index.html.erb
<h1 class="my-4">Lista kierowców</h1>

<p><%= link_to "Dodaj nowego kirowcę", new_driver_path, class: "btn btn-success" %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Imię</th>
      <th>Nazwisko</th>
      <th>Adres</th>
    </tr>
  </thead>
  <tbody>
    <% @drivers.each do |driver| %>
    <tr>
      <td><%= driver.id %></td>
      <td><%= driver.name %></td>
      <td><%= driver.surname %></td>
      <td><%= driver.address %></td>
      <td>
        <%= link_to 'Pokaż', driver_path(driver) %>
      </td>
    </tr>
    <% end %>
  </tbody>

app/views/drivers/new.html.erb
<h1 class="my-4"> Dodaj nowego kierowcę </h1>

<%= form_for @driver do |form| %>
  <p>
    <%= form.label :name, "Imie" %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :surname, "Nazwisko" %><br>
    <%= form.text_field :surname %>
  </p>

  <p>
    <%= form.label :address, "Adres" %><br>
    <%= form.text_field :address %>
  </p>

  <p>
    <%= form.submit "Utwórz", class: "btn btn-success" %>
  </p>
<% end %>

app/views/drivers/show.html.erb
<h1 class="my-4">Profil kierowcy</h1>

<h5>Nr id:</h5><p><strong><%= @driver.id %></strong></p>
<h5>Początek trasy:</h5><p><strong><%= @driver.name %></strong></p>
<h5>Koniec trasy:</h5><p><strong><%= @driver.surname %></strong></p>
<h5>Długość:</h5><p><strong><%= @driver.address %></strong></p>


<%= link_to 'Edytuj', edit_driver_path, class: "btn btn-primary" %>
<%= link_to 'Lista kierowców', drivers_path, class: "btn btn-secondary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MilleMigliaV3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>

    </div>
  </body>
</html>

app/views/tracks/_form.html.erb
<%= form_for @track do |form| %>
  <p>
    <%= form.label :star, "Początek trasy" %><br>
    <%= form.text_field :start %>
  </p>

  <p>
    <%= form.label :destination, "Koniec trasy" %><br>
    <%= form.text_field :destination %>
  </p>

  <p>
    <%= form.label :distance, "Długość" %><br>
    <%= form.text_field :distance %>
  </p>

  <%= form.label :driver_id, "Kierowca X" %><br>
  <%= form.select :driver_id, options_for_select(Driver.all.map {|d| ["#{d.name} #{d.surname}",d.id]}, @track.driver_id),  { include_blank: true }, class: "form-control custom-select" %>

  <p>
    <%= form.label :car, "Samochód" %><br>
    <%= form.text_field :car %>
  </p>

  <p>
    <%= form.label :description, "Opis" %><br>
    <%= form.text_field :description %>
  </p>

  <p>
    <%= form.submit button_name, class: "btn btn-success" %>
  </p>
<% end %>

app/views/tracks/edit.html.erb
<h1 class="my-4"> Edytuj trasę </h1>

<%= render partial: "form", locals: { button_name: "Zaspisz"} %>

app/views/tracks/index.html.erb
<h1 class="my-4">Lista tras</h1>

<p><%= link_to "Dodaj nową trasę", new_track_path, class: "btn btn-success" %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>#</th>
      <th>Początek</th>
      <th>Koniec</th>
      <th>Odległość</th>
      <th>Kierowca</th>
      <th>Samochód</th>
      <th>Opis</th>
    </tr>
  </thead>
  <tbody>
    <% @tracks.each do |track| %>
    <tr>
      <td><%= track.id %></td>
      <td><%= track.start %></td>
      <td><%= track.destination %></td>
      <td><%= track.distance %></td>
      <td><%= Driver.find(track.driver_id).name %> <%= Driver.find(track.driver_id).surname %></td>
      <td><%= track.car %></td>
      <td><%= track.description %></td>
      <td>
        <%= link_to 'Pokaż', track_path(track) %>
      </td>
    </tr>
    <% end %>
  </tbody>

app/views/tracks/new.html.erb
<h1 class="my-4"> Dodaj nową trasę </h1>

<%= render partial: "form", locals: { button_name: "Dodaj nową trasę"} %>

app/views/tracks/show.html.erb
<h1 class="my-4">Podgląd trasy</h1>

<h5>Nr id:</h5><p><strong><%= @track.id %></strong></p>
<h5>Początek trasy:</h5><p><strong><%= @track.start %></strong></p>
<h5>Koniec trasy:</h5><p><strong><%= @track.destination %></strong></p>
<h5>Długość:</h5><p><strong><%= @track.distance %></strong></p>
<h5>Kierowca:</h5><p><strong><%= @track.driver.name %> <%= @track.driver.surname %></strong></p>
<h5>Samochód:</h5><p><strong><%= @track.car %></strong></p>
<h5>Opis trasy:</h5><p><strong><%= @track.description %></strong></p>

<%= link_to 'Edytuj', edit_track_path, class: "btn btn-primary" %>
<%= link_to 'Lista tras', tracks_path, class: "btn btn-secondary" %>